ezplatform:
    system:
        site:
            content_view:
                full:
                    home_page:
                        controller: ez_query::pagingQueryAction
                        template: "@ezdesign/full/home_page.html.twig"
                        match:
                            Id\Location: 2
                        params:
                            query:
                                query_type: Contact
                                limit: 10
                                assign_results_to: contacts
                    test_contact:
                        controller: App\Controller\TestContactController::fullViewAction
                        template: "@ezdesign/full/test_contact.html.twig"
                        match:
                            Identifier\ContentType:
                                - test_contact
                line:
                    test_contact:
                        template: "@ezdesign/line/test_contact.html.twig"
                        match:
                            Identifier\ContentType:
                                - test_contact